name: "build-latest"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "master"
    paths:
      - "src/**"
  pull_request:
    branches:
      - "main"
      - "master"

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      dockerfiles: ${{ steps.filter.outputs.dockerfiles }}
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            dockerfiles:
              - "src/Dockerfile*"

  docker_buildx_debian:
    needs: changes
    if: needs.changes.outputs.dockerfiles == 'true' || github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Run Docker on tmpfs
        uses: JonasAlfredsson/docker-on-tmpfs@v2.0.0
        with:
          tmpfs_size: 7
          swap_size: 9

      - name: Perform setup steps
        uses: JonasAlfredsson/checkout-qemu-buildx@v2.0.0
        with:
          should_login: ${{ github.event_name != 'pull_request' }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push latest Debian image
        uses: docker/build-push-action@v7.0.0
        with:
          context: ./src
          file: ./src/Dockerfile
          platforms: |
            linux/amd64
            linux/386
            linux/arm64
            linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: emulator/docker-nginx-lego:latest

  docker_buildx_alpine:
    needs: changes
    if: needs.changes.outputs.dockerfiles == 'true' || github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Run Docker on tmpfs
        uses: JonasAlfredsson/docker-on-tmpfs@v2.0.0
        with:
          tmpfs_size: 7
          swap_size: 9

      - name: Perform setup steps
        uses: JonasAlfredsson/checkout-qemu-buildx@v2.0.0
        with:
          should_login: ${{ github.event_name != 'pull_request' }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push latest Alpine image
        uses: docker/build-push-action@v7.0.0
        with:
          context: ./src
          file: ./src/Dockerfile-alpine
          platforms: |
            linux/amd64
            linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: emulator/docker-nginx-lego:latest-alpine
